//

public class Concatenation
{
   public static void main(String[] args)
   {


         System.out.println("This line is too long and now it " +
                            "has spanned more than one line, which will cause a " + 
                             "syntax error to be generated by the compiler. ");

   }
}
